"""Skrip 20: Ekspor Gradient Boosting model ke TypeScript runtime
dan buat data sampel uji paritas.
"""

import os
import json
import joblib
import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MODEL_PATH = ROOT / "ML" / "outputs_umkm" / "best_model.pkl"
TS_OUTPUT_PATH = ROOT / "src" / "lib" / "prediction" / "tabular-umkm-model.ts"
PARITY_OUTPUT_PATH = ROOT / "ML" / "outputs_model_benchmark" / "gb_parity_samples.json"
TEST_DATA_PATH = ROOT / "ML" / "final_umkm" / "test.csv"

FEATURES = [
    "business_type_encoded", "month", "latest_usage_kwh", "previous_usage_kwh",
    "avg_3_month_usage_kwh", "avg_6_month_usage_kwh", "trend_1_month",
    "trend_3_month", "month_sin", "month_cos", "avg_tariff_idr_per_kwh",
]


def main():
    print("=== Exporting Gradient Boosting Model to TypeScript ===")
    
    if not MODEL_PATH.exists():
        print(f"Error: Model not found at {MODEL_PATH}")
        return
        
    model = joblib.load(MODEL_PATH)
    
    # Check model class name
    model_class = model.__class__.__name__
    print(f"Loaded model class: {model_class}")
    if model_class != "GradientBoostingRegressor":
        print(f"Error: Expected GradientBoostingRegressor, got {model_class}")
        return
        
    # Extract params
    init_value = float(model.init_.constant_[0][0])
    learning_rate = float(model.learning_rate)
    n_estimators = len(model.estimators_)
    print(f"n_estimators: {n_estimators}")
    print(f"learning_rate: {learning_rate}")
    print(f"init_value: {init_value}")
    
    # Extract trees
    trees = []
    for idx, estimator_arr in enumerate(model.estimators_):
        estimator = estimator_arr[0]
        tree = estimator.tree_
        
        trees.append({
            "children_left": tree.children_left.tolist(),
            "children_right": tree.children_right.tolist(),
            "features": tree.feature.tolist(),
            "thresholds": tree.threshold.tolist(),
            "values": tree.value.flatten().tolist()
        })
        
    # Generate TS file content
    ts_content = f"""/**
 * Gradient Boosting Regression Model - pure TypeScript inference.
 * Auto-generated by ML/scripts/20_export_gb_model_to_json.py.
 */

export const MODEL_NAME = "Gradient Boosting Regression" as const;
export const MODEL_VERSION = "Gradient Boosting UMKM v1.0" as const;

export const FEATURE_ORDER = [
  "business_type_encoded",
  "month",
  "latest_usage_kwh",
  "previous_usage_kwh",
  "avg_3_month_usage_kwh",
  "avg_6_month_usage_kwh",
  "trend_1_month",
  "trend_3_month",
  "month_sin",
  "month_cos",
  "avg_tariff_idr_per_kwh",
] as const;

export type TabularFeatureName = (typeof FEATURE_ORDER)[number];
export type TabularFeatureInput = Record<TabularFeatureName, number>;

const INIT_VALUE = {init_value};
const LEARNING_RATE = {learning_rate};

interface DecisionTree {{
  children_left: number[];
  children_right: number[];
  features: number[];
  thresholds: number[];
  values: number[];
}}

const TREES: DecisionTree[] = {json.dumps(trees, indent=2)};

function predictTree(tree: DecisionTree, features: number[]): number {{
  let node = 0;
  while (tree.children_left[node] !== -1) {{
    const featIdx = tree.features[node];
    const val = features[featIdx];
    if (val <= tree.thresholds[node]) {{
      node = tree.children_left[node];
    }} else {{
      node = tree.children_right[node];
    }}
  }}
  return tree.values[node];
}}

export function predictTabularUmkm(features: TabularFeatureInput): {{
  predictedUsageKwh: number;
  modelVersion: string;
  method: string;
}} {{
  // Build features array in FEATURE_ORDER
  const vector: number[] = new Array(FEATURE_ORDER.length);
  for (let i = 0; i < FEATURE_ORDER.length; i++) {{
    const name = FEATURE_ORDER[i];
    const val = features[name];
    if (typeof val !== "number" || !Number.isFinite(val)) {{
      throw new Error(
        `Tabular model: feature "${{name}}" must be a finite number, got ${{val}}`
      );
    }}
    vector[i] = val;
  }}

  // Accumulate prediction
  let y = INIT_VALUE;
  for (let i = 0; i < TREES.length; i++) {{
    y += LEARNING_RATE * predictTree(TREES[i], vector);
  }}

  // Clamp predictions to non-negative and minimum 10.0 kWh (same as Python logic)
  const predictedUsageKwh = parseFloat(Math.max(10.0, y).toFixed(2));

  return {{
    predictedUsageKwh,
    modelVersion: MODEL_VERSION,
    method: "TABULAR_MODEL",
  }};
}}
"""
    
    # Write TS file
    TS_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(TS_OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(ts_content)
    print(f"Exported TypeScript model file to {TS_OUTPUT_PATH}")
    
    # Export 20 sample tests for parity validation
    if TEST_DATA_PATH.exists():
        df_test = pd.read_csv(TEST_DATA_PATH)
        samples = df_test.sample(n=20, random_state=42)
        
        parity_samples = []
        for idx, row in samples.iterrows():
            feat_input = {f: float(row[f]) for f in FEATURES}
            python_pred = float(model.predict(pd.DataFrame([feat_input]))[0])
            python_pred = max(10.0, python_pred)
            
            parity_samples.append({
                "features": feat_input,
                "python_pred": round(python_pred, 4)
            })
            
        PARITY_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
        with open(PARITY_OUTPUT_PATH, "w", encoding="utf-8") as f:
            json.dump(parity_samples, f, indent=2)
        print(f"Saved 20 test samples to {PARITY_OUTPUT_PATH}")
    else:
        print(f"Warning: test.csv not found at {TEST_DATA_PATH}. Parity samples not generated.")


if __name__ == "__main__":
    main()
