import Link from 'next/link';
import { Activity, AlertTriangle, BarChart3, Gauge, Lightbulb, LineChart, LockKeyhole, SlidersHorizontal, TrendingUp } from 'lucide-react';
import { BusinessSelector, EmptyState, SoftCard, WorkspaceHeader, WorkspacePage } from '@/components/product/WorkspaceUI';
import { decimal, formatMonth, rupiah } from '@/lib/format';
import { requireWorkspacePage } from '@/server/services/workspace-page';
import { getDecisionSupport } from '@/server/services/workspace.service';
import { getUserEntitlements } from '@/server/services/entitlement.service';
import { analyzeLatestAnomaly, calculateEfficiencyScore, predictUsage } from '@/server/services/product-analysis';
import { Simulator } from '../predictions/Simulator';

export const dynamic = 'force-dynamic';
const tabs = [
  ['overview', Gauge, 'Ringkasan'], ['trend', LineChart, 'Tren'], ['anomaly', AlertTriangle, 'Anomali'],
  ['forecast', TrendingUp, 'Proyeksi'], ['recommendations', Lightbulb, 'Rekomendasi'], ['simulator', SlidersHorizontal, 'Simulator'],
] as const;

export default async function AnalysisPage({ searchParams }: { searchParams: Promise<{ businessId?: string | string[]; tab?: string | string[] }> }) {
  const query = await searchParams;
  const requestedBusinessId = typeof query.businessId === 'string' ? query.businessId : undefined;
  const requestedTab = typeof query.tab === 'string' ? query.tab : 'overview';
  const activeTab = tabs.some(([key]) => key === requestedTab) ? requestedTab : 'overview';
  const { userId } = await requireWorkspacePage(requestedBusinessId);
  const [data, entitlements] = await Promise.all([getDecisionSupport(userId, requestedBusinessId), getUserEntitlements(userId)]);
  const tariff = Number(data.business.tariffRupiahPerKwh ?? data.latestBill?.tariffRupiahPerKwh ?? 0) || null;
  const samples = [...data.bills].reverse().map((bill) => ({ period: bill.periodEnd.slice(0, 7), usageKwh: bill.kwh === null ? null : Number(bill.kwh), billAmount: Number(bill.totalAmountRupiah), tariff: bill.tariffRupiahPerKwh === null ? tariff : Number(bill.tariffRupiahPerKwh) }));
  const prediction = predictUsage(samples, tariff);
  const anomaly = analyzeLatestAnomaly(samples);
  const estimates = data.applianceEstimates.filter((item) => item.monthlyKwh !== null);
  const totalEstimate = estimates.reduce((sum, item) => sum + (item.monthlyKwh ?? 0), 0);
  const shares = estimates.map((item) => totalEstimate > 0 ? ((item.monthlyKwh ?? 0) / totalEstimate) * 100 : 0);
  const score = calculateEfficiencyScore({ bill: data.latestBill ? Number(data.latestBill.totalAmountRupiah) : null, revenue: data.matchingRevenue ? Number(data.matchingRevenue.amountRupiah) : null, hasTariff: tariff !== null, applianceShares: shares });
  const ratio = data.ratio;
  const businessQuery = `businessId=${encodeURIComponent(data.business.id)}`;
  const recommendations = [
    !data.latestBill && { priority: 'Tinggi', title: 'Catat tagihan terbaru', detail: 'Tagihan diperlukan sebagai dasar perbandingan dan analisis.' },
    !data.matchingRevenue && { priority: 'Sedang', title: 'Lengkapi pendapatan pada bulan yang sama', detail: 'Pendapatan membantu memberi konteks porsi biaya listrik terhadap omzet.' },
    tariff === null && { priority: 'Sedang', title: 'Lengkapi tarif rata-rata per kWh', detail: 'Tarif membantu mengubah pemakaian menjadi estimasi biaya.' },
    ratio !== null && ratio > 10 && { priority: ratio > 20 ? 'Tinggi' : 'Sedang', title: 'Pantau rasio listrik terhadap pendapatan', detail: `Porsi tercatat sekitar ${decimal.format(ratio)}%. Angka ini belum memperhitungkan biaya operasional lain.` },
    estimates[0] && { priority: 'Sedang', title: `Tinjau pola pakai ${estimates[0].appliance.name}`, detail: 'Prioritas berdasarkan daya, jumlah, dan jam pakai input; bukan pengukuran langsung alat.' },
  ].filter(Boolean) as Array<{ priority: string; title: string; detail: string }>;

  return <WorkspacePage>
    <WorkspaceHeader eyebrow="Pusat analisis" title="Analisis biaya & pemakaian" description="Satu tempat untuk membaca tren, indikasi anomali, proyeksi deterministik, rekomendasi, dan skenario. Semua hasil berbasis input Anda—bukan pengukuran real-time atau diagnosis teknis." actions={<BusinessSelector businesses={data.businesses} selectedId={data.business.id} route="/analysis"/>}/>
    <nav aria-label="Bagian analisis" className="flex gap-2 overflow-x-auto rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-2">{tabs.map(([key, Icon, label]) => <Link key={key} href={`/analysis?${businessQuery}&tab=${key}`} aria-current={activeTab === key ? 'page' : undefined} className={`inline-flex shrink-0 items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold ${activeTab === key ? 'bg-emerald-600 text-white' : 'text-[var(--muted)] hover:bg-[var(--surface-muted)] hover:text-[var(--foreground)]'}`}><Icon className="h-4 w-4"/>{label}</Link>)}</nav>
    {activeTab === 'overview' && <><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><SoftCard><Gauge className="h-5 w-5 text-emerald-600"/><p className="mt-3 text-xs font-bold uppercase text-slate-500">Skor efisiensi</p><p className="mt-1 text-3xl font-black text-emerald-950">{score.score ?? '—'}</p><p className="text-sm text-slate-500">{score.label} · keyakinan {score.confidence}</p></SoftCard><SoftCard><Activity className="h-5 w-5 text-emerald-600"/><p className="mt-3 text-xs font-bold uppercase text-slate-500">Status terbaru</p><p className="mt-1 text-xl font-black text-emerald-950">{anomaly.status}</p><p className="text-sm text-slate-500">{anomaly.differencePercent === null ? 'Perlu riwayat pembanding' : `${decimal.format(anomaly.differencePercent)}% dari baseline`}</p></SoftCard><SoftCard><TrendingUp className="h-5 w-5 text-emerald-600"/><p className="mt-3 text-xs font-bold uppercase text-slate-500">Proyeksi berikutnya</p><p className="mt-1 text-xl font-black text-emerald-950">{prediction.predictedUsageKwh === null ? 'Belum tersedia' : `${decimal.format(prediction.predictedUsageKwh)} kWh`}</p><p className="text-sm text-slate-500">Keyakinan {prediction.confidence ?? '—'}</p></SoftCard><SoftCard><BarChart3 className="h-5 w-5 text-emerald-600"/><p className="mt-3 text-xs font-bold uppercase text-slate-500">Rasio listrik</p><p className="mt-1 text-3xl font-black text-emerald-950">{ratio === null ? '—' : `${decimal.format(ratio)}%`}</p><p className="text-sm text-slate-500">Terhadap omzet bulan yang sama</p></SoftCard></section><SoftCard><h2 className="text-xl font-black text-emerald-950">Cara membaca hasil</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><p className="rounded-2xl bg-emerald-50 p-4 text-sm leading-6 text-emerald-950"><strong>Tren</strong><br/>Menunjukkan pola data historis, bukan kepastian periode berikutnya.</p><p className="rounded-2xl bg-amber-50 p-4 text-sm leading-6 text-amber-950"><strong>Anomali</strong><br/>Indikasi awal untuk ditinjau, bukan bukti kerusakan alat.</p><p className="rounded-2xl bg-cyan-50 p-4 text-sm leading-6 text-cyan-950"><strong>Proyeksi</strong><br/>Rumus deterministik tanpa AI/ML, randomness, atau API eksternal.</p></div></SoftCard></>}
    {activeTab === 'trend' && <SoftCard><div className="flex items-center justify-between"><div><h2 className="text-xl font-black text-emerald-950">Tren pemakaian & tagihan</h2><p className="mt-1 text-sm text-slate-500">Riwayat diurutkan berdasarkan periode tagihan.</p></div><LineChart className="h-6 w-6 text-emerald-600"/></div>{samples.length === 0 ? <div className="mt-6"><EmptyState icon="" title="Belum ada data" description="Tambahkan tagihan untuk membentuk tren." href="/bills/new" action="Tambah Tagihan"/></div> : <div className="mt-6 overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead><tr className="border-b border-emerald-900/10 text-xs uppercase text-slate-500"><th className="pb-3">Periode</th><th className="pb-3">Tagihan</th><th className="pb-3">kWh</th><th className="pb-3">Tarif</th></tr></thead><tbody>{[...data.bills].map((bill) => <tr key={bill.id} className="border-b border-emerald-900/5"><td className="py-4 font-bold">{formatMonth(bill.periodEnd)}</td><td className="py-4 font-bold text-emerald-700">{rupiah.format(bill.totalAmountRupiah)}</td><td className="py-4">{bill.kwh ?? 'Tidak diisi'}</td><td className="py-4">{bill.tariffRupiahPerKwh ? rupiah.format(Number(bill.tariffRupiahPerKwh)) : 'Tidak diisi'}</td></tr>)}</tbody></table></div>}</SoftCard>}
    {activeTab === 'anomaly' && <SoftCard><AlertTriangle className="h-7 w-7 text-amber-600"/><h2 className="mt-4 text-2xl font-black text-emerald-950">{anomaly.status}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">{anomaly.differencePercent === null ? 'Tambahkan satu periode historis untuk membentuk baseline.' : `Pemakaian terbaru ${anomaly.differencePercent >= 0 ? 'berada' : 'turun'} ${decimal.format(Math.abs(anomaly.differencePercent))}% dibanding rata-rata historis ${decimal.format(anomaly.baseline ?? 0)} kWh.`}</p><p className="mt-5 rounded-2xl bg-amber-50 p-4 text-sm text-amber-950">Ini adalah indikasi awal berbasis data input, bukan diagnosis teknis atau bukti kerusakan alat.</p></SoftCard>}
    {activeTab === 'forecast' && <SoftCard>{!entitlements.limits.detailedAnalysis && <div className="mb-5 flex items-start gap-3 rounded-2xl bg-slate-100 p-4"><LockKeyhole className="h-5 w-5 text-slate-600"/><p className="text-sm text-slate-600">Paket Gratis menampilkan ringkasan. Detail penyebab dan riwayat panjang tersedia pada Pro.</p></div>}<h2 className="text-xl font-black text-emerald-950">Proyeksi deterministik</h2>{prediction.hasPrediction ? <dl className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl bg-emerald-50 p-4"><dt className="text-xs font-bold uppercase text-emerald-700">Pemakaian</dt><dd className="mt-2 text-2xl font-black">{decimal.format(prediction.predictedUsageKwh ?? 0)} kWh</dd></div><div className="rounded-2xl bg-emerald-50 p-4"><dt className="text-xs font-bold uppercase text-emerald-700">Estimasi tagihan</dt><dd className="mt-2 text-lg font-black">{prediction.estimatedBill === null ? 'Tarif belum ada' : rupiah.format(prediction.estimatedBill)}</dd></div><div className="rounded-2xl bg-emerald-50 p-4"><dt className="text-xs font-bold uppercase text-emerald-700">Risiko kenaikan</dt><dd className="mt-2 text-lg font-black">{prediction.risk}</dd></div><div className="rounded-2xl bg-emerald-50 p-4"><dt className="text-xs font-bold uppercase text-emerald-700">Keyakinan</dt><dd className="mt-2 text-lg font-black">{prediction.confidence}</dd></div></dl> : <div className="mt-5"><EmptyState icon="" title="Belum dapat diproyeksikan" description="Tambahkan minimal satu catatan dengan kWh atau kombinasi tagihan dan tarif."/></div>}<p className="mt-5 text-sm text-slate-500">Metode: {prediction.method ?? 'belum tersedia'} · {prediction.historyMonths} bulan data · gap {prediction.gapMonths} bulan.</p></SoftCard>}
    {activeTab === 'recommendations' && <div className="grid gap-4 lg:grid-cols-3">{recommendations.length ? recommendations.map((item, index) => <SoftCard key={item.title}><span className="inline-flex rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-800">{item.priority} · {index + 1}</span><h2 className="mt-4 text-lg font-black text-emerald-950">{item.title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{item.detail}</p></SoftCard>) : <SoftCard className="lg:col-span-3"><EmptyState icon="" title="Belum ada prioritas tambahan" description="Data terkini tidak memicu aturan rekomendasi utama."/></SoftCard>}</div>}
    {activeTab === 'simulator' && <SoftCard><h2 className="text-xl font-black text-emerald-950">Simulator skenario alat</h2><p className="mt-2 text-sm text-slate-500">Berjalan di browser dan tidak mengubah data tersimpan.</p><div className="mt-6"><Simulator baseBill={data.latestBill ? Number(data.latestBill.totalAmountRupiah) : null} defaultTariff={tariff ?? 1444.7} applianceOptions={data.appliances.filter((item) => item.powerWatts !== null).map((item) => ({ name: item.name, powerWatts: item.powerWatts as number }))}/></div></SoftCard>}
  </WorkspacePage>;
}
