[mypy]
python_version = 3.11
strict = False
ignore_missing_imports = True
warn_unused_ignores = True
disable_error_code = no-any-return, arg-type, import-untyped, operator

[mypy-catboost.*]
ignore_missing_imports = True

[mypy-joblib.*]
ignore_missing_imports = True

[mypy-lightgbm.*]
ignore_missing_imports = True

[mypy-lightning.*]
ignore_missing_imports = True

[mypy-psutil.*]
ignore_missing_imports = True

[mypy-pyarrow.*]
ignore_missing_imports = True

[mypy-pytorch_forecasting.*]
ignore_missing_imports = True

[mypy-sklearn.*]
ignore_missing_imports = True
