import { redirect } from 'next/navigation';
import { SettingsTabs } from '@/components/product/SettingsTabs';
import { SoftCard, WorkspaceHeader, WorkspacePage } from '@/components/product/WorkspaceUI';
import { getOptionalSession } from '@/server/auth/session';
import { SecurityForm } from '../SecurityForm';
import { KeyRound, ShieldCheck } from 'lucide-react';

export const dynamic = 'force-dynamic';
export default async function SecuritySettingsPage() { const session = await getOptionalSession(); if (!session?.user) redirect('/login'); return <WorkspacePage><WorkspaceHeader eyebrow="Pengaturan akun" title="Keamanan" description="Perbarui kata sandi dan keluarkan sesi lain ketika Anda mencurigai akses yang tidak dikenal." /><SettingsTabs active="/settings/security" /><div className="grid gap-6 lg:grid-cols-[1fr_0.8fr]"><SoftCard><h2 className="mb-5 text-lg font-black">Ubah kata sandi</h2><SecurityForm /></SoftCard><SoftCard><ShieldCheck className="h-7 w-7 text-[var(--primary)]"/><h2 className="mt-4 text-lg font-black">Status akun</h2><dl className="mt-5 space-y-3 text-sm"><div className="rounded-xl bg-[var(--surface-muted)] p-4"><dt className="text-xs text-[var(--muted)]">Email login</dt><dd className="mt-1 font-bold">{session.user.email}</dd></div><div className="rounded-xl bg-[var(--surface-muted)] p-4"><dt className="text-xs text-[var(--muted)]">Sesi saat ini</dt><dd className="mt-1 font-bold text-[var(--primary)]">Aktif dan terlindungi</dd></div></dl><p className="mt-5 text-xs leading-5 text-[var(--muted)]">WattWise tidak pernah menampilkan kata sandi atau token sesi. Setelah kata sandi diubah, sesi lain akan dicabut.</p></SoftCard></div><SoftCard><div className="flex items-start gap-3"><KeyRound className="h-5 w-5 text-[var(--primary)]"/><div><h2 className="font-black">Passkey</h2><p className="mt-1 text-sm leading-6 text-[var(--muted)]">Ditunda secara eksplisit sampai tersedia integrasi passkey resmi yang kompatibel dengan Better Auth dan deployment Vercel. Build ini tidak membuat implementasi WebAuthn buatan sendiri.</p></div></div></SoftCard></WorkspacePage>; }
