-- Additive MVP 2 migration for saved analysis, recommendations, report history, and notifications.
ALTER TABLE "AnalysisResult" ADD COLUMN "previousMonthUsageKwh" DOUBLE PRECISION;
ALTER TABLE "AnalysisResult" ADD COLUMN "previousMonthCostIdr" DOUBLE PRECISION;
ALTER TABLE "AnalysisResult" ADD COLUMN "previousMonthKwhChangePct" DOUBLE PRECISION;
ALTER TABLE "AnalysisResult" ADD COLUMN "previousMonthCostChangePct" DOUBLE PRECISION;
ALTER TABLE "AnalysisResult" ADD COLUMN "threeMonthAverageKwh" DOUBLE PRECISION;
ALTER TABLE "AnalysisResult" ADD COLUMN "threeMonthAverageCostIdr" DOUBLE PRECISION;
ALTER TABLE "AnalysisResult" ADD COLUMN "threeMonthKwhChangePct" DOUBLE PRECISION;
ALTER TABLE "AnalysisResult" ADD COLUMN "threeMonthCostChangePct" DOUBLE PRECISION;
ALTER TABLE "AnalysisResult" ADD COLUMN "applianceEstimateKwh" DOUBLE PRECISION;
ALTER TABLE "AnalysisResult" ADD COLUMN "applianceGapPct" DOUBLE PRECISION;
ALTER TABLE "AnalysisResult" ADD COLUMN "usageStatusLabel" TEXT;
ALTER TABLE "AnalysisResult" ADD COLUMN "insights" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "AnalysisResult" ADD COLUMN "estimatedSavingsIdr" DOUBLE PRECISION;
ALTER TABLE "AnalysisResult" ADD COLUMN "disclaimer" TEXT;
ALTER TABLE "Recommendation" ADD COLUMN "estimatedSavingsKwh" DOUBLE PRECISION;
ALTER TABLE "Recommendation" ADD COLUMN "priority" TEXT;
ALTER TABLE "Recommendation" ADD COLUMN "impact" TEXT;
ALTER TABLE "Recommendation" ADD COLUMN "reason" TEXT;
ALTER TABLE "Recommendation" ADD COLUMN "practicalSteps" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Recommendation" ADD COLUMN "disclaimer" TEXT;
ALTER TABLE "Recommendation" ADD COLUMN "source" TEXT;
ALTER TABLE "Recommendation" ADD COLUMN "triggerApplianceName" TEXT;
CREATE INDEX "Recommendation_source_idx" ON "Recommendation"("source");
ALTER TABLE "MonthlyReport" ADD COLUMN "totalKwh" DOUBLE PRECISION;
ALTER TABLE "MonthlyReport" ADD COLUMN "totalCostIdr" DOUBLE PRECISION;
ALTER TABLE "MonthlyReport" ADD COLUMN "energyScore" DOUBLE PRECISION;
ALTER TABLE "MonthlyReport" ADD COLUMN "disclaimer" TEXT;
CREATE TABLE "Notification" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "businessId" TEXT, "title" TEXT NOT NULL, "message" TEXT NOT NULL, "type" TEXT NOT NULL, "isRead" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Notification_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Notification_userId_isRead_createdAt_idx" ON "Notification"("userId", "isRead", "createdAt");
CREATE INDEX "Notification_businessId_idx" ON "Notification"("businessId");
CREATE INDEX "Notification_type_idx" ON "Notification"("type");
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE ON UPDATE CASCADE;
