import { redirect } from 'next/navigation';
import { SettingsTabs } from '@/components/product/SettingsTabs';
import { SoftCard, WorkspaceHeader, WorkspacePage } from '@/components/product/WorkspaceUI';
import { getOptionalSession } from '@/server/auth/session';
import { getUserSettings } from '@/server/services/workspace.service';
import { updateProfileAction } from '../actions';
import { deleteAccountAction } from '../actions';
import { UserRound } from 'lucide-react';

export const dynamic = 'force-dynamic';
export default async function ProfileSettingsPage({ searchParams }: { searchParams: Promise<{ saved?: string; delete?: string }> }) {
  const session = await getOptionalSession(); if (!session?.user) redirect('/login');
  const settings = await getUserSettings(session.user.id); const query = await searchParams;
  return <WorkspacePage><WorkspaceHeader eyebrow="Pengaturan akun" title="Profil Anda" description="Perbarui nama yang ditampilkan di ruang kerja WattWise. Alamat email tetap menjadi identitas login Anda." /><SettingsTabs active="/settings/profile" />{query.saved && <div role="status" className="rounded-2xl bg-emerald-500/10 p-4 text-sm font-semibold text-emerald-600 dark:text-emerald-400">Profil berhasil diperbarui.</div>}{query.delete === 'invalid' && <div role="alert" className="rounded-2xl bg-rose-500/10 p-4 text-sm font-semibold text-rose-600 dark:text-rose-400">Ketik HAPUS AKUN persis untuk melanjutkan.</div>}<div className="grid gap-6 lg:grid-cols-[1fr_0.8fr]"><SoftCard><h2 className="text-lg font-black text-[var(--foreground)]">Informasi profil</h2><form action={updateProfileAction} className="mt-5 space-y-4"><label className="block"><span className="mb-1.5 block text-xs font-bold text-[var(--foreground)]">Nama lengkap</span><input name="name" required minLength={2} maxLength={100} defaultValue={settings.profile?.name} className="w-full rounded-xl border border-[var(--border)] bg-[var(--surface-muted)] px-3 py-3 text-[var(--foreground)]" /></label><label className="block"><span className="mb-1.5 block text-xs font-bold text-[var(--foreground)]">Alamat email</span><input disabled value={settings.profile?.email ?? ''} className="w-full rounded-xl border border-[var(--border)] bg-[var(--surface-muted)] px-3 py-3 text-[var(--muted)]" /></label><button className="rounded-xl bg-emerald-600 px-5 py-3 text-sm font-extrabold text-white hover:bg-emerald-700">Simpan Profil</button></form></SoftCard><SoftCard><UserRound className="h-7 w-7 text-[var(--primary)]"/><h2 className="mt-4 text-lg font-black text-[var(--foreground)]">Ruang kerja yang lebih personal</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Nama profil digunakan pada navigasi dan konteks akun. Data usaha, tagihan, dan diagnosis tidak berubah saat nama diperbarui.</p></SoftCard></div><SoftCard className="border-rose-500/30"><h2 className="text-lg font-black text-rose-600 dark:text-rose-400">Hapus akun dan seluruh data</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Tindakan permanen ini menghapus akun, usaha, tagihan, diagnosis, dan laporan terkait melalui cascade database. Ketik <strong>HAPUS AKUN</strong> untuk mengonfirmasi.</p><form action={deleteAccountAction} className="mt-5 flex flex-col gap-3 sm:flex-row"><input name="confirmation" required autoComplete="off" className="min-w-0 flex-1 rounded-xl border border-rose-500/30 bg-[var(--surface)] px-3 py-2.5 text-[var(--foreground)]"/><button className="rounded-xl bg-rose-700 px-4 py-2.5 text-sm font-bold text-white">Hapus Akun Permanen</button></form></SoftCard></WorkspacePage>;
}
