name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Laravel CI
    runs-on: ubuntu-latest

    env:
      APP_ENV: testing
      APP_DEBUG: "false"
      CACHE_STORE: array
      SESSION_DRIVER: array
      QUEUE_CONNECTION: sync
      DB_CONNECTION: sqlite
      DB_DATABASE: ":memory:"

    defaults:
      run:
        working-directory: watt